### ISSUE TITLE
Increase width of refguide content + use responsive for portrait

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2784]
Currently the reference guide #content div has `max-width: 62.5em` set.
This is a bit on the low end for large screens in landscape mode, and could instead be set to eg. `60%`.
Beyond that the rendering is starting to feel too large for paragraphs, but at 60% most large codeblocks read far better.

For phones, detecting portrait orientation and setting the `max-width` to `100%` would also be a plus:

```css
@media (orientation: portrait) {
    #header, #content, #footnotes, #footer {
        max-width: 100%;
    }
}
```
